# Install Rest client extension in vs code to hit api's directly from here
@serverUrl = http://localhost:8000
# @serverUrl =


# ======================== Auth API ========================


### =========================================
### Signup - Valid
@baseAuthUrl = {{serverUrl}}/api/auth
### =========================================
POST {{baseAuthUrl}}/signup
Content-Type: application/json

{
  "name": "Yeeshu",
  "email": "yeeshu@test.com",
  "password": "Pass1234"
}



### =========================================
### Signup - Duplicate Email
### =========================================
POST {{baseAuthUrl}}/signup
Content-Type: application/json

{
  "name": "Another User",
  "email": "yeeshu@test.com",
  "password": "Pass1234"
}



### =========================================
### Signup - Invalid Password (Too Weak)
### =========================================
POST {{baseAuthUrl}}/signup
Content-Type: application/json

{
  "name": "Weak User",
  "email": "weak@test.com",
  "password": "123"
}



### =========================================
### Login - Valid
### =========================================
POST {{baseAuthUrl}}/login
Content-Type: application/json

{
  "email": "yeeshu@test.com",
  "password": "Pass1234"
}



### =========================================
### Login - Wrong Password
### =========================================
POST {{baseAuthUrl}}/login
Content-Type: application/json

{
  "email": "yeeshu@test.com",
  "password": "WrongPass"
}



### =========================================
### Login - Non Existing User
### =========================================
POST {{baseAuthUrl}}/login
Content-Type: application/json

{
  "email": "nouser@test.com",
  "password": "Pass1234"
}


###
# ======================== Matches API ========================
GET {{serverUrl}}/matches/
Content-Type: application/json

###

POST {{serverUrl}}/matches/
Content-Type: application/json

{
    "sport": "football",
		"homeTeam": "Team A",
		"awayTeam": "Team B",
		"startTime": "2024-06-01T15:00:00Z",
		"endTime": "2024-06-01T17:00:00Z",
		"homeScore": 2,
		"awayScore": 1
}

###
# ======================== Commentaries API ========================
@matchId = 2
GET {{serverUrl}}/matches/{{matchId}}/commentary/
Content-Type: application/json

###

POST {{serverUrl}}/matches/{{matchId}}/commentary/
Content-Type: application/json

{
  "minute": 45,
	"sequence": 120,
	"period": "second",
	"eventType": "goal",
	"actor": "Alex Doe",
	"team": "Team A",
	"message": "Goal scored by Alex Doe for Team A",
	"metadata": {"assist": "john doe"} ,
	"tags": ["goal", "shot"]
}
