name: Client CICD

on:
  workflow_dispatch:
  push:
    branches:
      - "**"
    paths:
      - ".github/workflows/client.yaml"
  pull_request:
    branches: [main]
    paths:
      - "client/**/*"
      - ".github/workflows/client.yaml"

jobs:
  client:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
          cache-dependency-path: client/pnpm-lock.yaml

      - name: Install client dependencies
        working-directory: client
        run: pnpm install --frozen-lockfile

      - name: Ensure Docker is installed
        run: |
          if command -v docker >/dev/null 2>&1; then
            echo "Docker is already installed. Skipping installation."
          else
            echo "Docker not found. Installing..."
            sudo apt-get update
            sudo apt-get install -y docker.io
          fi
          docker --version

      - name: Build client using docker
        working-directory: client
        run: docker build -t stathub-client .
