name: Client CICD

on:
  workflow_dispatch:
  push:
  pull_request:
    branches: [main]
    paths:
      - "client/**/*"
      - ".github/workflows/client.yaml"

jobs:
  client:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          cache: true

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24.14.0
          cache: pnpm
          cache-dependency-path: client/pnpm-lock.yaml

      - name: Ensure Docker is installed
        run: |
          if command -v docker >/dev/null 2>&1; then
            echo "Docker is already installed. Skipping installation."
          else
            echo "Docker not found. Installing..."
            sudo apt-get update
            sudo apt-get install -y docker.io
          fi
          docker --version

      - name: Build client using docker
        working-directory: client
        run: docker build -t stathub-client .
