name: Client CICD

on:
  workflow_dispatch:
  push:
    branches:
      - "**"
    paths:
      - "client/**/*"
  pull_request:
    branches: [main]
    paths:
      - "client/**/*"

jobs:
  client:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
          cache-dependency-path: client/pnpm-lock.yaml

      - name: Install client dependencies
        working-directory: client
        run: pnpm install --frozen-lockfile

      - name: Build client
        working-directory: client
        run: pnpm run build
