name: Code Quality Checks

on:
  workflow_call:
  workflow_dispatch:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  quality-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24.14.0
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Install root dependencies
        run: |
          pnpm install --frozen-lockfile --ignore-scripts
          pip install pre-commit

      - name: Run Biome lint and format
        run: pnpm run check-lint-format

      - name: Run pre-commit
        run: pre-commit run --all-files
