name: Server CICD

on:
  workflow_dispatch:
  push:
    branches:
      - "**"
    paths:
      - ".github/workflows/server.yaml"
  pull_request:
    branches: [main]
    paths:
      - "server/**/*"
      - ".github/workflows/server.yaml"

jobs:
  server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
          cache-dependency-path: server/pnpm-lock.yaml

      - name: Install server dependencies
        working-directory: server
        run: pnpm install
