name: Server CICD

on:
  workflow_dispatch:
  # push:
  # pull_request:
  #   branches: [main]
  #   paths:
  #     - "server/**/*"
  #     - ".github/workflows/server.yaml"

jobs:
  server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          cache: true

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24.14.0
          cache: pnpm
          cache-dependency-path: server/pnpm-lock.yaml

      - name: Install server dependencies
        working-directory: server
        run: pnpm install
